repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.3'
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [ python, pyi, jupyter ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
